### ISSUE TITLE
Is it possible to directly replace the seal-cuda in Pencil with origianl microsoft seal library?

### ISSUE THREAD

**Issue by blossomin** [lightbulb128/Pencil#3]
Or do you have any advice for this replacement, since I want to see the pure CPU performance without GPU acceleration

**Comment by lightbulb128** [comment]
This repository does not support CPU computation, since the `seal-cuda` repository we are using gives no convenient way to conduct the GPU computation to CPU. I am implementing a new version of seal-cuda [here](https://github.com/lightbulb128/troy-nova), which support both CPU and GPU computation, but transporting this repo Pencil to it is another story.

**Comment by lightbulb128** [comment]
I don't think MS's seal could be directly used since we are using pack lwes which was not originally supported in SEAL.

**Comment by blossomin** [comment]
I asked this question because you mentioned your seal-cuda has a similar interface with MS's seal,

**Comment by blossomin** [comment]
and in your paper, you mentioned:
_For a complete comparison, we also implement the SIMD encoding/decoding functionality used in SEAL. The results are listed in Table VI. On average, our hardware implementation achieves 10× acceleration over CPU implementation._

so this comparison is not running the MPC training, just some encoding/decoding functions?
I'm not clear about how this *10x* is calculated.

**Comment by lightbulb128** [comment]
> and you mentioned the following result in your paper: _For a complete comparison, we also implement the SIMD encoding/decoding functionality used in SEAL. The results are listed in Table VI. On average, our hardware implementation achieves 10× acceleration over CPU implementation._
> 
> so this comparison is not running the MPC training, just some encoding/decoding functions? I'm not clear about how this **10x** is calculated.

We compared the common operations (eg plaintext encoding/decoding, plain-cipher multiplication) that are both implemented in seal-cuda and Microsoft SEAL. We did not implement end-to-end training with MS SEAL, as some features are only implemented in our seal-cuda, for example LWE packing.

**Comment by blossomin** [comment]
Thanks for your reply, so how do you get the conclusion of **On average, our hardware implementation achieves 10× acceleration over CPU implementation.**, by averaging the accelerating rate in the table VI?

**Comment by lightbulb128** [comment]
> I asked this question because you mentioned your seal-cuda has a similar interface with MS's seal,
> 
> do you have any idea about the labor needed to port the Pencil to use new seal-cuda repo?

I believe porting Pencil to the new seal-cuda repo will be much easier than porting it to MS SEAL, because all seal-cuda's features are also supported in the new implementation.

**Comment by blossomin** [comment]
I see you are still working on the new seal-cuda repo, I also want to confirm: all the old seal-cuda features are supported in the new repo(both CPU and GPU version)?

**Comment by lightbulb128** [comment]
That 10x is a rough summary of the table, since the most time-consuming ops in both matmul and conv2d are plain-cipher mult.

Yes, I think all the features are supported. I would happily provide support and update commits if anything is missing.
